### ISSUE TITLE
IE11 overwriting users session when trying to print page

### ISSUE THREAD

**Issue by DanielConnelly** [hmrc/platui-support#10]
## Description of the issue

When a user prints a page on MDTP while using IE11, IE11 reloads all the static files without passing the mdtp cookie due to sameSite: Lax, this causes a brand new cookie to be created and overwrite the valid mdtp cookie and therefore invalidate the user session, this forces the user to log in again. 

The issue is a mix of strange IE behaviour with sameSite and always creating an mdtp cookie on calls due to turning session into cookie even if it is not required. 

These issues combined cause very annoying user behaviour and can interrupt desired flows. 

in play-frontend-hmrc we noticed during investigating this issue that when IE11 prints it reloads all static files and due to an attribute on <image src="/goods-movement-system/hmrc-frontend/assets/govuk/images/govuk-logotype-crown.png" xlink:href="" ... this causes a 404 to be registered as xlink:href="" forces a call to the route context of the url e.g if you print on a/b/c IE11 will call a/b and fail. 

## Steps to reproduce the issue

Open any user authenticated service that contains hmrc frontend code in IE11 

Ctrl + p on the page

reload the page 
## Actual vs expected behaviour

Actual 
The user losses their auth session and is forced to re-login 

Expected 
The user's session should be persisted and allow the user to continue 

## Environment (where applicable)

- Operating system: Windows 10 
- Browser: IE 
- Browser version: IE11 
- Library Name & Version: N/A

**Comment by oscarduignan** [comment]
Thank you @DanielConnelly, I've created a bug ticket in our backlog to tackle the further investigation of this issue and possible solutions PLATUI-1593

**Comment by ellamdav** [comment]
Whilst we've investigated this and made some tweaks under PLATUI-1593 and PLATUI-1619, we don't believe it's something we can fix for all users right now.  There's some wider work coming up to look at how static assets are served on the platform, which might have the side effect of reducing the impact of this issue.
