### ISSUE TITLE
UR Banner - add heading for navigation and identification

### ISSUE THREAD

**Issue by adamliptrot-oc** [hmrc/platui-support#14]
## Library or service name

https://github.com/hmrc/play-frontend-hmrc

## Related component

UR Banner

## Context

The UR banner has been flagged by DAC in a couple of audits as having what looks like a heading but is not a heading, prompting confusion at it not showing up in the heading list / be skipped over when navigating by heading.

https://github.com/hmrc/play-frontend-hmrc/blob/main/src/main/twirl/uk/gov/hmrc/hmrcfrontend/views/components/HmrcUserResearchBanner.scala.html#L26

Seems a fair issue when similar temporary banners have h2 to aid navigation.

The fix would be to add a heading (eg a h2 to stay with the cookie banner / error summary / notification banner pattern of things above the h1 getting an h2).

**Comment by JoPintoPaul** [comment]
Hi @adamliptrot-oc, thank you for raising this Github issue. PlatUI are now reviewing your issue. The next step will be for us to assign one of the following labels: accepted, cantfix, invalid, wontfix. We’ll update on this issue when a label is assigned.

**Comment by ellamdav** [comment]
Raised Jira ticket [PLATUI-1721](https://jira.tools.tax.service.gov.uk/browse/PLATUI-1721) to fix.

**Comment by JoPintoPaul** [comment]
@adamliptrot-oc This work has now been completed, and released in v3.18.0 of play-frontend-hmrc:
https://github.com/hmrc/play-frontend-hmrc/releases/tag/v3.18.0
