### ISSUE TITLE
UR Banner - make close link copy make sense when out of context

### ISSUE THREAD

**Issue by adamliptrot-oc** [hmrc/platui-support#15]
## Library or service name

https://github.com/hmrc/play-frontend-hmrc

## Related component

UR Banner

## Context

DAC have raised the issue of the close link a couple of times in audits.

As it only says “No thanks” it goes against the principle of being able to identify the link’s purpose when viewed out of context. 

https://github.com/hmrc/play-frontend-hmrc/blob/main/src/main/twirl/uk/gov/hmrc/hmrcfrontend/views/components/HmrcUserResearchBanner.scala.html#L42

As such it should probably be something like
> “No thanks, I don’t want to take part in user research”

 (with the additional text visually hidden - I struggled to come up with a short way of saying it where all the text could be visible).

**Comment by JoPintoPaul** [comment]
Hi @adamliptrot-oc, thank you for raising this Github issue. PlatUI are now reviewing your issue. The next step will be for us to assign one of the following labels: **accepted**, **cantfix**, **invalid**, **wontfix**. We’ll update on this issue when a label is assigned.

**Comment by terrysimpson99** [comment]
How about:
_“No, I do not want to take part in user research”_

- Removed _"thanks"_. Users shouldn't need to say thank you for selecting an option. See https://www.gov.uk/service-manual/design/writing-for-user-interfaces#tone

- Replaced _"don't"_ with _"do not"_. Contractions are only an option for positive terms. See https://www.gov.uk/service-manual/design/writing-for-user-interfaces#style

**Comment by ellamdav** [comment]
Thank you for raising this feature request. We’ve reviewed your suggestion within PlatUI, and we have opened a Jira Task ticket to work on this suggestion. You can track this ticket on our board via [PLATUI-1723](https://jira.tools.tax.service.gov.uk/browse/PLATUI-1723).

Thank you for this suggestion to improve our products.

**Comment by oscarduignan** [comment]
@adamliptrot-oc the change has been merged into hmrc-frontend from version 5.0.6 and play-frontend-hmrc from version  3.19.0

We'll make some posts to promote the releases in slack 👍
