### ISSUE TITLE
Language changing interaction with query parameters

### ISSUE THREAD

**Issue by jmountain-hmrc** [hmrc/platui-support#17]
## Library or service name
hmrc-frontend

## Library version (where applicable)
3.11.0-play-28

## Description of the issue
The language changing routes that come from the hmrc-frontend library have some interesting behaviour with how they seem to be interacting with URLs - we’ve encountered an issue where query parameters with strange or unusual characters can get mutated or cause errors in when switching between languages - 

## Steps to reproduce the issue
An example is listed below. The first image is showing the query parameter as a pound sign “query=£“, but switching the language then changes this to “query=%A3”. Switching this then back causes an error below on the “hmrc-frontend/language/en” route. This was performed on the ATED_LOOKUP_ALL service profile

![image](https://user-images.githubusercontent.com/31282623/165797447-4eabe899-fe16-4d4e-9163-c3aa3bfef9c6.png)

## Actual vs expected behaviour
Expected behaviour: Changing the language should probably not interfere with the query parameters provided if possible
Actual behaviour: Changing the language malforms the query parameters and can eventually produce an error.

## Environment (where applicable)

- Operating system: Mac OS
- Browser: Firefox
- Browser version: 99

**Comment by ellamdav** [comment]
Thank you for raising this Github issue. PlatUI are now reviewing your issue. The next step will be for us to assign one of the following labels: accepted, cantfix, invalid, wontfix. We’ll update on this issue when a label is assigned.

**Comment by ellamdav** [comment]
Raised Jira ticket [PLATUI-1722](https://jira.tools.tax.service.gov.uk/browse/PLATUI-1722) to fix.

**Comment by oscarduignan** [comment]
@jmountain-hmrc we've just released a fix for this, if you can [update your version of play-frontend-hmrc to 3.17.0](https://github.com/hmrc/play-frontend-hmrc/blob/main/CHANGELOG.md#3170---2022-05-12) or if you can't, then update play-language directly to [5.3.0](https://github.com/hmrc/play-language/releases/tag/v5.3.0) you should get the fix. [Here's the PR with the fix from play language](https://github.com/hmrc/play-language/pull/43)
