### ISSUE TITLE
Support HmrcTimeoutDialog in Multiple languages

### ISSUE THREAD

**Issue by AKKUM** [hmrc/platui-support#20]
## Library or service name
play-frontend-hmrc

## Related component
Not Sure

## Context
Trying to implement Timeout Dialog pop-up in multiple language. All looks good  apart from countdown Minutes, Seconds.

## Alternatives
Not using. As our app has multiple languages off in prod.

## Additional information (if applicable)
https://hmrcdigital.slack.com/archives/CJMUM9AG3/p1658299795118819) @oscarduignan suggested to create new issue here.

**Comment by JoPintoPaul** [comment]
Thank you for raising this feature request. We’ve reviewed your suggestion within PlatUI, and we have opened a Jira Story ticket to carry out further analysis on this suggestion. You can track this ticket on our board via [this link](https://jira.tools.tax.service.gov.uk/browse/PLATUI-1897).

Thank you for this suggestion to improve our products.

**Comment by JoPintoPaul** [comment]
Closing issue on this Github repository as we have now migrated to a Jira ticket, please track work there.
