### ISSUE TITLE
Add print css support to play-frontend-hmrc library

### ISSUE THREAD

**Issue by Ashwani1403** [hmrc/platui-support#22]
## Library or service name

Play-frontend-hmrc library

## Related component

This is related to when a user tries to print(ctrl+p) and save the form page as pdf's. 

## Context

Our CSG Forms (former Print and Post) team , we re-build quite a few print and post form service (e.g. SC2, SC3,CH2) using latest play-frontend-hmrc library. 
In all of our internal accessibility audit's we have noticed that whenever user tries to save the page as pdf(ctrl+p) there are several items which provide no benefit on the printed output(for e.g. Beta phase banner with feedback link
Change links on Check Your Answers page, Back link, Is this page not working properly? (opens in new tab) link, Footer links), hence needs to hidden.
To fix this one way to apply print.css and import it via main frontend.css for each frontend microservice's (and add classes to various components all over the place around ~350 forms shortlisted). Which doesn't looks the right thing.

## Alternatives

If there could be a more global, central, consistent approach like to automatically get all these print style classes from play-frontend-hmrc library itself rather than making individual changes in each service.

## Additional information (if applicable)

https://github.com/hmrc/accessibility-audits-external/issues/4265

**Comment by ellamdav** [comment]
Apologies for the very late response here - this repo was deprecated some time back but not archived, so we've missed a handful of reported issues.

We'll be looking at this under PLATUI-2617, to identify any similar components and ticket up the work to add the print styles.
