### ISSUE TITLE
HMRC Frontend - Account header - Links are not scaling with browser settings

### ISSUE THREAD

**Issue by danielelder** [hmrc/platui-support#25]
## Library or service name

HMRC Frontend - Account header

https://design.tax.service.gov.uk/hmrc-design-patterns/account-header/

## Library version (where applicable)

5.27.0

## Description of the issue

When increasing the font size within Chrome's browser settings the text size of all elements on the page increases apart from the account header menu links.

It looks like the links are missing a relative css font value (rem), for example adding `font-size: 1rem;` appears fix the issue when added via the dev tools.

```
.hmrc-account-menu__link {
  ...
  ...
  font-size: 16px;
  font-size: 1rem;
  ....
}
```

## Steps to reproduce the issue

Open the example in Chrome:

https://design.tax.service.gov.uk/examples/account-header/example/

Goto Settings --> Appearance --> Customise fonts

Set font size to 24px

View the account header example page and it will look similar to the screenshot below

<img width="1098" alt="Screenshot of account header with large fonts" src="https://user-images.githubusercontent.com/16639519/228260584-d4202f4b-85a3-45ab-9412-907319f37ee3.png">

## Actual vs expected behaviour

All text should be increased proportionally to the users preference, similar to the screenshot below:

<img width="1096" alt="Screenshot 2023-03-28 at 10 50 33" src="https://user-images.githubusercontent.com/16639519/228261675-8951fccf-19a6-48bf-8583-f641c42242de.png">

## Environment (where applicable)

- Operating system: MacOS 13.1
- Browser: Chrome
- Browser version: 110.0.5481.100

**Comment by ellamdav** [comment]
Apologies for the very late response here - this repo was deprecated some time back but not archived, so we've missed a handful of reported issues.

We'll be tracking a fix for this under PLATUI-2618
