### ISSUE TITLE
govukTable should support attributes being added to thead and tr

### ISSUE THREAD

**Issue by habeeb01** [hmrc/platui-support#4]
## Related component
`uk.gov.hmrc.govukfrontend.views.html.components.GovukTable`

## Context
We are trying to implement a responsive table. In order to do this I need to be able add attributes to several table elements. govukTable allows attributes to be added to `table`, `th` & `td`. But not `thead` & `tr` (this is required for our responsive implementation). Here is a link to what we want to implement, https://gist.github.com/adamliptrot-oc/d44f2cff20e364277da68166ed869c11 

## Alternatives
The current workaround is to write the raw html.

**Comment by kyle-bowden** [comment]
[Resource](https://gist.github.com/adamliptrot-oc/d44f2cff20e364277da68166ed869c11) on how to add responsiveness to a table component.

**Comment by oscarduignan** [comment]
Hi @habeeb01 thank you for raising this, I think we might have misunderstood your suggestion here. I'm going to raise this next week with our PO to see if we can spend some time looking at the current API for the GovukTable component and the guidance from DIAS to see what options there are for any possible changes to make it easier to use the responsive table pattern 👍

**Comment by oscarduignan** [comment]
Hi @habeeb01 apologies, I forgot to let you know the jira ticket number after I created one so you can track this further, it's PLATUI-1613

**Comment by oscarduignan** [comment]
To update this, we've done some research under that ticket and we've asked for a slot to discuss what we found at the next hmrc design resources working group. Where we'll try to clarify recommended approaches to create responsive tables and agree what we can do to help make following these approaches easier in our libraries

The working group meets every two weeks, but I'm not sure when next one will because it currently coincides with good friday easter holiday, meaning it may end up being 3 weeks until we can come back with anything more on this

**Comment by ellamdav** [comment]
Apologies for the very late response here - this repo was deprecated some time back but not archived, so we've neglected a handful of reported issues.

We don't currently support responsive tables in play-frontend-hmrc, and the HMRC Design Resources group feel that, as a GOVUK component, any such enhancements should come from upstream in GDS.  Whilst there is some mention of responsive tables in the [GOVUK Design System backlog](https://github.com/alphagov/govuk-design-system-backlog/issues/61), it doesn't look like anything will be added anytime soon.

In the interim, we'll be playing a spike PLATUI-2622 to see if there's any workaround we can provide, or else to provide guidance on how to fork components in the library and what that means in terms of ongoing maintenance and support.
